apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "app.fullname" . }}-webcam
  labels: {{ include "app.labels" . | nindent 4 }}
{{ if .Values.route.govonly }}
  annotations:
    haproxy.router.openshift.io/ip_whitelist: 142.34.53.0/24 142.22.0.0/15 142.24.0.0/13 142.32.0.0/13
{{ end }}
spec:
  to:
    kind: Service
    name: {{ template "app.fullname" . }}
    weight: 100
  port:
    targetPort: nginx
  tls:
    termination: edge  
  host: {{ .Values.route.host  }}
  path: {{ .Values.route.webcamPath  }}


---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "app.fullname" . }}-replaytheday
  labels: {{ include "app.labels" . | nindent 4 }}
{{ if .Values.route.govonly }}
  annotations:
    haproxy.router.openshift.io/ip_whitelist: 142.34.53.0/24 142.22.0.0/15 142.24.0.0/13 142.32.0.0/13
{{ end }}
spec:
  to:
    kind: Service
    name: {{ template "app.fullname" . }}
    weight: 100
  port:
    targetPort: nginx
  tls:
    termination: edge  
  host: {{ .Values.route.host  }}
  path: {{ .Values.route.replayTheDayPath  }}