kind: Secret
apiVersion: v1
metadata:
  name: {{ template "app.fullname" . }}-django
  labels: {{ include "app.labels" . | nindent 4 }}   
data:
  BCEID_CLIENT_ID: ''
  BCEID_SECRET: ''
  DRIVEBC_ROUTE_PLANNER_API_AUTH_KEY: ''
  SECRET_KEY: ''
type: Opaque