kind: Secret
apiVersion: v1
metadata:
  name: {{ template "app.fullname" . }}-django
  labels: {{ include "app.labels" . | nindent 4 }}   
data:
  SECRET_KEY: 
  DRIVEBC_ROUTE_PLANNER_API_AUTH_KEY: 
type: Opaque