kind: Secret
apiVersion: v1
metadata:
  name: {{ template "app.fullname" . }}-static
  labels: {{ include "app.labels" . | nindent 4 }}   
data:
  GEOCODER_API_AUTH_KEY: ''
  ROUTE_PLANNER_KEY: ''
type: Opaque