x-function: &backend
  build:
    context: .
    dockerfile: ./compose/backend/Dockerfile

  volumes:
    - ./src/backend:/app/backend

  environment:
    - DATABASE_URL=postgres://drivebc:Passw0rd!@postgres:5432/drivebc?sslmode=disabl
    - DB_ENGINE=django.contrib.gis.db.backends.postgis
    - REDIS_HOST=redis
    - REDIS_URL=redis://localhost:6379
    - REDIS_PORT=6379
    - DB_NAME=drivebc
    - DB_USER=drivebc
    - DB_PASSWORD=Passw0rd!
    - DB_HOST=db
    - DJANGO_CORS_ORIGIN_WHITELIST=http://localhost:8000,http://localhost:3000
    - DJANGO_SUPERUSER_USERNAME=admin
    - DJANGO_SUPERUSER_EMAIL=admin@oxd.com
    - DJANGO_SUPERUSER_PASSWORD=admin123
    - DRIVEBC_ROUTE_PLANNER_API_AUTH_KEY=Pgct8pXbdig7N2PLS8NKiOZATe5V3Fun
    # - EMAIL_HOST=mailhog

  stdin_open: true
  tty: true
  depends_on:
    - db
    - redis

volumes:
  redis:
  postgres:
    driver: local

services:

  django:
    <<: *backend
    container_name: django
    ports:
      - "8000:8000"
    command: /start.sh

  # static:
  #   container_name: static
  #   command: npm start

  node:
    container_name: node
    build:
      context: ./src/frontend
      dockerfile: ../../compose/frontend/Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=openssl-legacy-provider
    depends_on:
      - django
    command: npm start

  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=drivebc
      - POSTGRES_USER=drivebc
      - POSTGRES_PASSWORD=Passw0rd!
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: "redis:6.2"
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
