x-function: &backend
  env_file: .env

  build:
    context: .
    dockerfile: ./compose/backend/Dockerfile

  volumes:
    - ./src/backend:/app/backend

  stdin_open: true
  tty: true
  depends_on:
    - db
    - redis

volumes:
  redis:
  postgres:
    driver: local

services:
  django:
    <<: *backend
    container_name: django
    ports:
      - "8000:8000"
    command: /start.sh

  # static:
  #   container_name: static
  #   command: npm start

  node:
    env_file: .env
    container_name: node
    build:
      context: ./src/frontend
      dockerfile: ../../compose/frontend/Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - django
    command: npm start

  db:
    env_file: .env
    image: postgis/postgis:15-3.3-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: "redis:6.2"
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
