fullnameOverride: dev-django
namespace: c59ecc-tools #enter the full namespace here to the deployment has the correct imagestream


deployment:
  image: #by default use the image from the ImageStream
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 150m
      memory: 512Mi
  env:
    postgresSecret: dev-drivebc-pguser-dev-drivebc
    djangoConfigMap: dev-drivebc-django
    djangoSecret: dev-drivebc-django

route:
  host: drivebc.apps.silver.devops.gov.bc.ca
  backendpath: /backend/ #must be surrounded by /
  apipath: /api/ #must be surrounded by /
  govonly: true #Set to true so limited access is limited to gov IP's only. False for public access

pvc:
  port: 3000
  storage: 1Gi
