apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ template "app.fullname" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: redis:7