apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "app.fullname" . }}-backend
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ template "app.fullname" . }}
  port:
    targetPort: 80-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
  host: {{ .Values.route.host  }}