fullnameOverride: tasks
namespace:  #enter the full namespace here to the deployment has the correct imagestream


deployment:
  djangoImageName:  #by default use the image from the ImageStream
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 150m
      memory: 512Mi
  env:
    postgresSecret: dev-drivebc-pguser-dev-drivebc
    djangoConfigMap: dev-drivebc-django
    djangoSecret: dev-drivebc-django

