---
# Source: main/charts/django/templates/django-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dev-django
  labels: 
    helm.sh/chart: django-0.1.0
    app.kubernetes.io/name: django
    app.kubernetes.io/instance: drivebc-dev
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - name: 80-tcp
      port: 80
      targetPort: 8000
      protocol: TCP
  internalTrafficPolicy: Cluster
  selector:
    
    app.kubernetes.io/name: django
    app.kubernetes.io/instance: drivebc-dev
