nameOverride: prod-drivebc
fullnameOverride: prod-drivebc

django:
  fullnameOverride: prod-django
  nameOverride: prod-django
  replicaCount: 3
  image:
    repository: ghcr.io/bcgov/drivebc-django
    tag: latest-prod
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 250Mi
      limits:
        cpu: 1000m
        memory: 350Mi
    env:
      postgresSecret: prod-drivebc-pguser-prod-drivebc
      djangoConfigMap: prod-drivebc-django
      djangoSecret: prod-drivebc-django
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 200
  route:
    host: prod-drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: true #Set to true if you want to limit IP's that can access publicly available pages to the the addresses in the ipallowlist 
    iprestrictedAdminPages: true #Set to true if you want to limit IP's that can access backend admin pages
  mediapvc:
    storage: 1Gi
  apppvc:
    storage: 1Gi

tasks:
  fullnameOverride: prod-tasks
  nameOverride: prod-tasks
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-django
    tag: latest-prod
  deployment:
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        cpu: 750m
        memory: 250Mi
    volumes:
      claimName: prod-django-app-images
    env:
      postgresSecret: prod-drivebc-pguser-prod-drivebc
      djangoConfigMap: prod-drivebc-django
      djangoSecret: prod-drivebc-django

image-caching:
  fullnameOverride: prod-image-caching
  nameOverride: prod-image-caching
  replicaCount: 3
  image:
    repository: ghcr.io/bcgov/drivebc-image-caching
    tag: latest-prod
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 250m
        memory: 150Mi
    env:
      imagecachingConfigMap: prod-drivebc-image-caching
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 200
  route:
    host: prod-drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: true #Set to true if you want to limit IP's the the addresses in the ipallowlist 

redis:
  fullnameOverride: prod-redis
  nameOverride: prod-redis
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-redis
    tag: latest-prod
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 100Mi

static:
  fullnameOverride: prod-static
  nameOverride: prod-static
  replicaCount: 3
  image:
    repository: ghcr.io/bcgov/drivebc-static
    tag: latest-prod
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 250m
        memory: 150Mi
    env:
      staticConfigMap: prod-drivebc-static
      staticSecret: prod-drivebc-static
    volumes:
      imagesClaimName: prod-django-app-images
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 200
  route:
    host: prod-drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: true  #Set to true if you want to limit IP's the the addresses in the ipallowlist 
  logpvc:
    storage: 5Gi

logprocessing:
  fullnameOverride: logprocessing
  nameOverride: logprocessing
  image:
    repository: ghcr.io/bcgov/drivebc-logprocessing
    tag: latest
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi
    env:
      s3Secret: prod-drivebc-logprocessing
    volumes:
      logPVC: prod-static-log-storage