nameOverride: test-drivebc
fullnameOverride: test-drivebc

django:
  fullnameOverride: test-django
  nameOverride: test-django
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-django
    tag: latest-test
  deployment:
    resources:
      requests:
        cpu: 20m
        memory: 250Mi
      limits:
        cpu: 500m
        memory: 350Mi
    env:
      postgresSecret: test-drivebc-pguser-test-drivebc
      djangoConfigMap: test-drivebc-django
      djangoSecret: test-drivebc-django
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 75
  route:
    host: test-drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: false #Set to true if you want to limit IP's the the addresses in the ipallowlist 
  pvc:
    port: 3000
    storage: 1Gi

tasks:
  fullnameOverride: test-tasks
  nameOverride: test-tasks
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-django
    tag: latest-test
  deployment:
    resources:
      requests:
        cpu: 20m
        memory: 150Mi
      limits:
        cpu: 250m
        memory: 200Mi
    env:
      postgresSecret: test-drivebc-pguser-test-drivebc
      djangoConfigMap: test-drivebc-django
      djangoSecret: test-drivebc-django

image-caching:
  fullnameOverride: test-image-caching
  nameOverride: test-image-caching
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-image-caching
    tag: latest-test
  deployment:
    resources:
      requests:
        cpu: 20m
        memory: 50Mi
      limits:
        cpu: 250m
        memory: 100Mi
    env:
      imagecachingConfigMap: test-drivebc-image-caching
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 75
  route:
    host: test-drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: false #Set to true if you want to limit IP's the the addresses in the ipallowlist 

redis:
  fullnameOverride: test-redis
  nameOverride: test-redis
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-redis
    tag: latest-test
  deployment:
    resources:
      requests:
        cpu: 20m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi

static:
  fullnameOverride: test-static
  nameOverride: test-static
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-static
    tag: latest-test
  deployment:
    resources:
      requests:
        cpu: 20m
        memory: 50Mi
      limits:
        cpu: 150m
        memory: 100Mi
    env:
      staticConfigMap: test-drivebc-static
      staticSecret: test-drivebc-static
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 75
  route:
    host: test-drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: false  #Set to true if you want to limit IP's the the addresses in the ipallowlist 
