nameOverride: test-drivebc
fullnameOverride: test-drivebc

django:
  fullnameOverride: test-django
  nameOverride: test-django
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-django
    tag: latest-test
  deployment:
    resources:
      requests:
        cpu: 20m
        memory: 300Mi
      limits:
        cpu: 500m
        memory: 350Mi
    env:
      postgresSecret: test-drivebc-pguser-test-drivebc
      djangoConfigMap: test-drivebc-django
      djangoSecret: test-drivebc-django
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 75
  route:
    host: test-drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: false #Set to true if you want to limit IP's that can access publicly available pages to the the addresses in the ipallowlist 
    iprestrictedAdminPages: false #Set to true if you want to limit IP's that can access backend admin pages
  mediapvc:
    storage: 1Gi
  apppvc:
    storage: 1Gi
  podDisruptionBudget: 
    enabled: false 
    minAvailable:  

tasks:
  fullnameOverride: test-tasks
  nameOverride: test-tasks
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-django
    tag: latest-test
  deployment:
    resources:
      requests:
        cpu: 500m
        memory: 250Mi
      limits:
        cpu: 750m
        memory: 300Mi
    volumes:
      claimName: test-django-app-images
    env:
      postgresSecret: test-drivebc-pguser-test-drivebc
      djangoConfigMap: test-drivebc-django
      djangoSecret: test-drivebc-django

redis:
  fullnameOverride: test-redis
  nameOverride: test-redis
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-redis
    tag: latest-test
  deployment:
    resources:
      requests:
        cpu: 20m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi

static:
  fullnameOverride: test-static
  nameOverride: test-static
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-static
    tag: latest-test
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 250m
        memory: 150Mi
    env:
      staticConfigMap: test-drivebc-static
    volumes:
      imagesClaimName: test-django-app-images
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 75
  route:
    host: test-drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: false  #Set to true if you want to limit IP's the the addresses in the ipallowlist 
  logpvc:
    storage: 1Gi
  podDisruptionBudget: 
    enabled: false 
    minAvailable:  

openshiftjobs:
  fullnameOverride: test-openshiftjobs
  nameOverride: test-openshiftjobs

  image:
    repository: ghcr.io/bcgov/drivebc-openshiftjobs
    tag: latest-test

  cronjobs:
    analyzeuploadlogs:
      name: analyzeuploadlogs
      schedule: '0 9 * * *'  #NOTE: This is in UTC
      deployment:
        resources:
          requests:
            cpu: 50m
            memory: 150Mi
          limits:
            cpu: 150m
            memory: 300Mi
        env:
          s3Secret: test-drivebc-cronjob-s3bucket
        volumes:
          logs: test-static-log-storage

    ziplogs:
      name: ziplogs
      schedule: '30 * * * *'
      deployment:
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 150m
            memory: 200Mi
        volumes:
          logs: test-static-log-storage

    backupmediapvc:
      name: backupmediapvc
      schedule: '0 8 * * *'
      deployment:
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 250Mi
        env:
          s3Secret: test-drivebc-cronjob-s3bucket
        volumes:
          media: test-django