nameOverride: prod-drivebc
fullnameOverride: prod-drivebc

django:
  fullnameOverride: prod-django
  nameOverride: prod-django
  replicaCount: 3
  image:
    repository: ghcr.io/bcgov/drivebc-django
    tag: latest-prod
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 250Mi
      limits:
        cpu: 1000m
        memory: 350Mi
    env:
      postgresSecret: prod-drivebc-pguser-prod-drivebc
      djangoConfigMap: prod-drivebc-django
      djangoSecret: prod-drivebc-django
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 75
  route:
    host: prod-drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: true #Set to true if you want to limit IP's that can access publicly available pages to the the addresses in the ipallowlist 
    iprestrictedAdminPages: true #Set to true if you want to limit IP's that can access backend admin pages
  pvc:
    port: 3000
    storage: 1Gi

tasks:
  fullnameOverride: prod-tasks
  nameOverride: prod-tasks
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-django
    tag: latest-prod
  deployment:
    resources:
      requests:
        cpu: 75m
        memory: 150Mi
      limits:
        cpu: 250m
        memory: 200Mi
    env:
      postgresSecret: prod-drivebc-pguser-prod-drivebc
      djangoConfigMap: prod-drivebc-django
      djangoSecret: prod-drivebc-django

image-caching:
  fullnameOverride: prod-image-caching
  nameOverride: prod-image-caching
  replicaCount: 3
  image:
    repository: ghcr.io/bcgov/drivebc-image-caching
    tag: latest-prod
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 250m
        memory: 100Mi
    env:
      imagecachingConfigMap: prod-drivebc-image-caching
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 75
  route:
    host: prod-drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: true #Set to true if you want to limit IP's the the addresses in the ipallowlist 

redis:
  fullnameOverride: prod-redis
  nameOverride: prod-redis
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-redis
    tag: latest-prod
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi

static:
  fullnameOverride: prod-static
  nameOverride: prod-static
  replicaCount: 3
  image:
    repository: ghcr.io/bcgov/drivebc-static
    tag: latest-prod
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 150m
        memory: 100Mi
    env:
      staticConfigMap: prod-drivebc-static
      staticSecret: prod-drivebc-static
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 75
  route:
    host: prod-drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: true  #Set to true if you want to limit IP's the the addresses in the ipallowlist 
