nameOverride: dev-drivebc
fullnameOverride: dev-drivebc

django:
  fullnameOverride: dev-django
  nameOverride: dev-django
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-django
    tag: latest-dev
  deployment:
    resources:
      requests:
        cpu: 20m
        memory: 250Mi
      limits:
        cpu: 500m
        memory: 350Mi
    env:
      postgresSecret: dev-drivebc-pguser-dev-drivebc
      djangoConfigMap: dev-drivebc-django
      djangoSecret: dev-drivebc-django
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 75
  route:
    host: dev-drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: false #Set to true if you want to limit IP's that can access publicly available pages to the the addresses in the ipallowlist 
    iprestrictedAdminPages: false #Set to true if you want to limit IP's that can access backend admin pages
  mediapvc:
    storage: 1Gi
  apppvc:
    storage: 1Gi

tasks:
  fullnameOverride: dev-tasks
  nameOverride: dev-tasks
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-django
    tag: latest-dev
  deployment:
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 500m
        memory: 250Mi
    volumes:
      claimName: dev-django-app-images
    env:
      postgresSecret: dev-drivebc-pguser-dev-drivebc
      djangoConfigMap: dev-drivebc-django
      djangoSecret: dev-drivebc-django

redis:
  fullnameOverride: dev-redis
  nameOverride: dev-redis
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-redis
    tag: latest-dev
  deployment:
    resources:
      requests:
        cpu: 20m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi

static:
  fullnameOverride: dev-static
  nameOverride: dev-static
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-static
    tag: latest-dev
  deployment:
    resources:
      requests:
        cpu: 20m
        memory: 50Mi
      limits:
        cpu: 150m
        memory: 100Mi
    env:
      staticConfigMap: dev-drivebc-static
      staticSecret: dev-drivebc-static
    volumes:
      imagesClaimName: dev-django-app-images

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 75
  route:
    host: dev-drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: false  #Set to true if you want to limit IP's the the addresses in the ipallowlist 
  logpvc:
    storage: 1Gi

logprocessing:
  fullnameOverride: dev-logprocessing
  nameOverride: dev-logprocessing
  image:
    repository: ghcr.io/bcgov/drivebc-logprocessing
    tag: latest-dev
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 500Mi
      limits:
        cpu: 500m
        memory: 1Gi
    env:
      s3Secret: dev-drivebc-logprocessing
    volumes:
      logPVC: dev-static-log-storage