nameOverride: drivebc
fullnameOverride: drivebc

django:
  fullnameOverride: django
  nameOverride: django
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-django
    tag: latest
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 250Mi
      limits:
        cpu: 500m
        memory: 350Mi
    env:
      postgresSecret: drivebc-pguser-drivebc
      djangoConfigMap: drivebc-django
      djangoSecret: drivebc-django
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 75
  route:
    host: drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: false #Set to true if you want to limit IP's the the addresses in the ipallowlist 
  pvc:
    port: 3000
    storage: 1Gi

tasks:
  fullnameOverride: tasks
  nameOverride: tasks
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-django
    tag: latest
  deployment:
    resources:
      requests:
        cpu: 75m
        memory: 150Mi
      limits:
        cpu: 250m
        memory: 200Mi
    env:
      postgresSecret: drivebc-pguser-drivebc
      djangoConfigMap: drivebc-django
      djangoSecret: drivebc-django

image-caching:
  fullnameOverride: image-caching
  nameOverride: image-caching
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-image-caching
    tag: latest
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 250m
        memory: 100Mi
    env:
      imagecachingConfigMap: drivebc-image-caching
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 75
  route:
    host: drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: false #Set to true if you want to limit IP's the the addresses in the ipallowlist 

redis:
  fullnameOverride: redis
  nameOverride: redis
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-redis
    tag: latest
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi

static:
  fullnameOverride: static
  nameOverride: static
  replicaCount: 1
  image:
    repository: ghcr.io/bcgov/drivebc-static
    tag: latest
  deployment:
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 150m
        memory: 100Mi
    env:
      staticConfigMap: drivebc-static
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 75
  route:
    host: drivebc.apps.gold.devops.gov.bc.ca
    iprestricted: false  #Set to true if you want to limit IP's the the addresses in the ipallowlist 
