# See https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#global-chart-values
global:
  licensePlate: c59ecc
  namespace: tools

nameOverride: drivebc
fullnameOverride: drivebc


django:
  fullnameOverride: django
  namespace: c59ecc-tools #The namespace you are running the application on. This is used to pull from the ImageStream
  deployment:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 150m
        memory: 512Mi
    env:
      postgresSecret: drivebc-pguser-drivebc #By default this should be correct for Dev
      djangoConfigMap: drivebc-django #By default this should be correct for Dev
      djangoSecret: drivebc-django #By default this should be correct for dev
  route:
    host: drivebc.apps.silver.devops.gov.bc.ca
    backendpath: /backend/ #must be surrounded by /
    apipath: /api/ #must be surrounded by /
    govonly: true #Set to true so limited access is limited to gov IP's only. False for public access
  pvc:
    port: 3000
    storage: 1Gi


tasks:
  fullnameOverride: tasks
  namespace: c59ecc-tools #enter the full namespace here to the deployment has the correct imagestream
  deployment:
    djangoImageName: django #Since it needs to use the django imagestream. 
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 150m
        memory: 512Mi
    env:
      postgresSecret: drivebc-pguser-drivebc #By default this should be correct for Dev
      djangoConfigMap: drivebc-django #By default this should be correct for Dev
      djangoSecret: drivebc-django #By default this should be correct for dev

image-caching:
  fullnameOverride: image-caching
  namespace: c59ecc-tools #enter the full namespace here to the deployment has the correct imagestream
  environment: dev #enter the environment this is being deployed too. Needed to set the configmap reference
  deployment:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi
  route:
    host: drivebc.apps.silver.devops.gov.bc.ca
    govonly: true #Set to true so limited access is limited to gov IP's only. False for public access
    webcamPath: /webcam/
    replayTheDayPath: /ReplayTheDay/

redis:
  fullnameOverride: redis
  namespace: c59ecc-tools #enter the full namespace here to the deployment has the correct imagestream
  deployment:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi

static:
  fullnameOverride: static
  namespace: c59ecc-tools #enter the full namespace here to the deployment has the correct imagestream

  deployment:
    replicas: 2
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi

  route:
    host: drivebc.apps.silver.devops.gov.bc.ca
    govonly: true #Set to true so limited access is limited to gov IP's only. False for public access
