fullnameOverride: 
namespace: c59ecc-tools #enter the full namespace here to the deployment has the correct imagestream


deployment:
  image: #by default use the image from the ImageStream
  replicas: 2
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi

route:
  host: drivebc.apps.silver.devops.gov.bc.ca
  iprestricted: true #Set to true if you want to limit IP's the the addresses in the ipallowlist below
  ipallowlist: 142.34.53.0/24 142.22.0.0/15 142.24.0.0/13 142.32.0.0/13 208.181.128.46/32 #The first 4 ranges are GOV IP's, the last one is for OXD external IP
