

fullnameOverride: openshiftjobs
nameOverride: openshiftjobs

image:
  repository: ghcr.io/bcgov/drivebc-openshiftjobs
  tag: latest

cronjobs:
  analyzeuploadlogs:
    name: analyzeuploadlogs
    schedule: '0 9 * * *'  #NOTE: This is in UTC
    deployment:
      resources:
        requests:
          cpu: 50m
          memory: 1Gi
        limits:
          cpu: 2000m
          memory: 2Gi
      env:
        s3Secret: drivebc-cronjob-s3bucket
      volumes:
        logs: static-log-storage

  ziplogs:
    name: ziplogs
    schedule: '30 * * * *'
    deployment:
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 150m
          memory: 200Mi
      volumes:
        logs: static-log-storage

  backupmediapvc:
    name: backupmediapvc
    schedule: '0 8 * * *'
    deployment:
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 250Mi
      env:
        s3Secret: drivebc-cronjob-s3bucket
      volumes:
        media: django
