---
# Source: main/charts/redis/templates/redis-imageStream.yaml
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: dev-redis
  labels: 
    helm.sh/chart: redis-0.1.0
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: drivebc-dev
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: redis
