name: Unit tests on dev branch

on:
  push:
    branches: [ "bugfix/ga-unit-tests" ]
env:
  POSTGRES_DB: testdb
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpw

jobs:
  run-tests:
    runs-on: postgis:15-3.4

    services:
      redis:
        image: redis:6.2
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./src/backend/requirements/development.txt
    - name: Run Tests
      env:
        DB_NAME: testdb
        DB_USER: testuser
        DB_PASSWORD: testpw
        DB_HOST: localhost
        DB_PORT: 5432
        REDIS_HOST: redis
        REDIS_PORT: 6379
        DEBUG: false
        DJANGO_URL: http://localhost:8000
        DJANGO_ALLOWED_HOSTS: localhost
        DJANGO_CORS_ORIGIN_WHITELIST: http://localhost:8000,http://localhost:3000
        DJANGO_SUPERUSER_USERNAME: testvar
        DJANGO_SUPERUSER_EMAIL: testvar@testvar.com
        DJANGO_SUPERUSER_PASSWORD: testvar
        DJANGO_CSRF_COOKIE_SECURE: false
        DJANGO_SECURE_SSL_REDIRECT: false
        DJANGO_SESSION_COOKIE_SECURE: false
        DJANGO_EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
        DJANGO_EMAIL_HOST: testvar
        DJANGO_EMAIL_PORT: 1
        DJANGO_RECAPTCHA_SECRET_KEY: testvar
        DJANGO_FEEDBACK_EMAIL_DEFAULT: testvar@testvar.com
        DRIVEBC_INLAND_FERRY_API_BASE_URL: testvar
        DRIVEBC_IMAGE_API_BASE_URL: testvar
        DRIVEBC_IMAGE_PROXY_URL: testvar
        DRIVEBC_OPEN_511_API_BASE_URL: testvar
        DRIVEBC_WEBCAM_API_BASE_URL: testvar
        DRIVEBC_ROUTE_PLANNER_API_BASE_URL: testvar
        DRIVEBC_ROUTE_PLANNER_API_AUTH_KEY: testvar
        DRIVEBC_DIT_API_BASE_URL: testvar
        DRIVEBC_WEATHER_API_BASE_URL: testvar
        DRIVEBC_WEATHER_API_TOKEN_URL: testvar
        WEATHER_CLIENT_ID: testvar
        WEATHER_CLIENT_SECRET: testvar
        DRIVEBC_WEATHER_AREAS_API_BASE_URL: testvar
        SECRET_KEY: testvar
      run: |
        coverage run ./src/backend/manage.py test --noinput
