name: Deploy main to test

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build Docker images
    environment: test

    steps:
    - name: checkout code
      uses: actions/checkout@v3
