name: Weekly Trivy Image Scans
# Set to run on the latest-test image.

on:
  schedule:
    # Runs every week at 02:00 Sunday Morning.
    - cron:  '0 2 * * 0'
  workflow_dispatch:

permissions: 
    packages: read
    security-events: write

jobs:

  imagescan-static:
    name: Scan latest-test Static Image
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'ghcr.io/bcgov/drivebc-static:latest-test'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'


  imagescan-django:
    name: Scan latest-test django Image
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'ghcr.io/bcgov/drivebc-django:latest-test'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  imagescan-redis:
    name: Scan latest-test Redis Image
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'ghcr.io/bcgov/drivebc-redis:latest-test'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'


  imagescan-openshiftjobs:
    name: Scan latest-test OpenshiftJobs Image
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'ghcr.io/bcgov/drivebc-openshiftjobs:latest-test'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'


