name: OWASP ZAP Full Scan
on: workflow_dispatch

permissions:
  contents: read
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP Test Site
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: "https://dev-drivebc.apps.silver.devops.gov.bc.ca/"
#          rules_file_name: ".zap/rules.tsv"
