name: Weekly OWASP ZAP Full Scan
on:
  schedule:
    # Runs every week at 01:00 Sunday Morning.
    - cron:  '0 1 * * 0'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP Test Site
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: "https://test-drivebc.apps.gold.devops.gov.bc.ca/"
#          rules_file_name: ".zap/rules.tsv"